ALTER TABLE [dbo].[ACCOUNT_TEAM] DROP CONSTRAINT [FK_ACCOUNT_TEAM_TEAMS];
GO
ALTER TABLE [dbo].[ACCOUNT_TEAM]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_TEAM_TEAMS] FOREIGN KEY([TEAMID])
REFERENCES [dbo].[TEAMS] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ACCOUNT_TEAM] CHECK CONSTRAINT [FK_ACCOUNT_TEAM_TEAMS]
GO

ALTER TABLE [dbo].[RESOURCEFORPROJECT] DROP CONSTRAINT [FK_RESOURCEFORPROJECT_PROJECTS]
GO
ALTER TABLE [dbo].[RESOURCEFORPROJECT]  WITH CHECK ADD  CONSTRAINT [FK_RESOURCEFORPROJECT_PROJECTS] FOREIGN KEY([PROJECTID])
REFERENCES [dbo].[PROJECTS] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RESOURCEFORPROJECT] CHECK CONSTRAINT [FK_RESOURCEFORPROJECT_PROJECTS]
GO

ALTER TABLE [dbo].[RESOURCEFORPROJECT] DROP COLUMN INUSE;
GO

ALTER TABLE [dbo].[RESOURCEFORTASK] DROP CONSTRAINT [FK_RESOURCEFORTASK_TASKS];
GO
ALTER TABLE [dbo].[RESOURCEFORTASK]  WITH NOCHECK ADD  CONSTRAINT [FK_RESOURCEFORTASK_TASKS] FOREIGN KEY([TASKID])
REFERENCES [dbo].[TASKS] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RESOURCEFORTASK] NOCHECK CONSTRAINT [FK_RESOURCEFORTASK_TASKS]
GO

ALTER TABLE [dbo].[RESOURCEFORTASK] DROP COLUMN INUSE;
GO

ALTER TABLE PROJECTS ADD TEAMID INT NOT NULL;
GO

ALTER TABLE [dbo].[PROJECTS]  WITH CHECK ADD  CONSTRAINT [FK_PROJECTS_TEAMS] FOREIGN KEY([TEAMID])
REFERENCES [dbo].[TEAMS] ([ID])
GO
ALTER TABLE [dbo].[PROJECTS] CHECK CONSTRAINT [FK_PROJECTS_TEAMS]
GO

/****** Object:  View [dbo].[V_PROJECTS]    Script Date: 12.01.2020 15:26:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [dbo].[V_PROJECTS]
AS
	SELECT 
		P.ID, 
		P.NAME, 
		P.DESCRIPTION, 
		T.NAME TEAM,
		P.INUSE 
	FROM PROJECTS P
	JOIN TEAMS T ON T.ID = P.TEAMID
GO

