/*
   sobota, 11 stycznia 202010:35:36
   User: 
   Server: PCV2\SQLEXPRESS17
   Database: WM
   Application: 
*/
ALTER TABLE TASKS DROP CONSTRAINT FK_TASKS_TEAMS;
GO
EXEC sp_rename 'dbo.TASKS.TEAMID', 'ACCOUNTID', 'COLUMN';
GO

ALTER TABLE [dbo].[TASKS]  WITH CHECK ADD  CONSTRAINT [FK_TASKS_ACCOUNTS] FOREIGN KEY([ACCOUNTID])
REFERENCES [MGMNT].[ACCOUNTS] ([ID])
GO

/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TASKS
	DROP CONSTRAINT FK_TASKS_ACCOUNTS
GO
ALTER TABLE MGMNT.ACCOUNTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TASKS
	DROP CONSTRAINT FK_TASKS_PROJECTS
GO
ALTER TABLE dbo.PROJECTS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Tmp_TASKS
	(
	ID int NOT NULL IDENTITY (1, 1),
	PROJECTID int NOT NULL,
	ACCOUNTID int NOT NULL,
	NAME nvarchar(200) NOT NULL,
	STATE int NOT NULL,
	DESCRIPTION nvarchar(MAX) NULL,
	MODUSER nvarchar(260) NULL,
	MODCOMP nvarchar(260) NULL,
	INUSE bit NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE dbo.Tmp_TASKS SET (LOCK_ESCALATION = TABLE)
GO
SET IDENTITY_INSERT dbo.Tmp_TASKS ON
GO
IF EXISTS(SELECT * FROM dbo.TASKS)
	 EXEC('INSERT INTO dbo.Tmp_TASKS (ID, PROJECTID, ACCOUNTID, NAME, DESCRIPTION, MODUSER, MODCOMP, INUSE)
		SELECT ID, PROJECTID, ACCOUNTID, NAME, DESCRIPTION, MODUSER, MODCOMP, INUSE FROM dbo.TASKS WITH (HOLDLOCK TABLOCKX)')
GO
SET IDENTITY_INSERT dbo.Tmp_TASKS OFF
GO
ALTER TABLE dbo.TASKTIMES
	DROP CONSTRAINT FK_TASKTIMES_TASKS
GO
ALTER TABLE dbo.RESOURCEFORTASK
	DROP CONSTRAINT FK_RESOURCEFORTASK_TASKS
GO
DROP TABLE dbo.TASKS
GO
EXECUTE sp_rename N'dbo.Tmp_TASKS', N'TASKS', 'OBJECT' 
GO
ALTER TABLE dbo.TASKS ADD CONSTRAINT
	PK_TASKS PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.TASKS WITH NOCHECK ADD CONSTRAINT
	FK_TASKS_PROJECTS FOREIGN KEY
	(
	PROJECTID
	) REFERENCES dbo.PROJECTS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TASKS
	NOCHECK CONSTRAINT FK_TASKS_PROJECTS
GO
ALTER TABLE dbo.TASKS WITH NOCHECK ADD CONSTRAINT
	FK_TASKS_ACCOUNTS FOREIGN KEY
	(
	ACCOUNTID
	) REFERENCES MGMNT.ACCOUNTS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TASKS
	NOCHECK CONSTRAINT FK_TASKS_ACCOUNTS
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RESOURCEFORTASK WITH NOCHECK ADD CONSTRAINT
	FK_RESOURCEFORTASK_TASKS FOREIGN KEY
	(
	TASKID
	) REFERENCES dbo.TASKS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.RESOURCEFORTASK
	NOCHECK CONSTRAINT FK_RESOURCEFORTASK_TASKS
GO
ALTER TABLE dbo.RESOURCEFORTASK SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.TASKTIMES WITH NOCHECK ADD CONSTRAINT
	FK_TASKTIMES_TASKS FOREIGN KEY
	(
	TASKID
	) REFERENCES dbo.TASKS
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.TASKTIMES
	NOCHECK CONSTRAINT FK_TASKTIMES_TASKS
GO
ALTER TABLE dbo.TASKTIMES SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
