/****** Object:  View [dbo].[V_PROJECTSTAT]    Script Date: 13.01.2020 23:38:39 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   VIEW [dbo].[V_PROJECTSTAT]
AS
WITH CTE_TASKSTATES AS (
	SELECT PROJECTID, [0] NEW, [1] ACTIVE, [2] [SUSPEND], [3] [COMPLETE] FROM (
		SELECT PROJECTID, [STATE] FROM TASKS
	) T
	PIVOT (
	COUNT([STATE])
	FOR STATE IN ([0], [1], [2], [3])) PIV
)
, CTE_TIME AS (
	SELECT PROJECTID, SUM(WORKTIME) WORKTIME, SUM(DATEDIFF(SECOND, ESTIMATESTART, DATEADD(DAY,1,ESTIMATEEND))) ESTIMATEWORKTIME, 
		   (1 - (SUM(EXCEEDED+0.0)/COUNT(1)))*100 PUNCTUALITY 
	FROM V_TIMESTAT
	GROUP BY PROJECTID
)
SELECT P.ID PROJECTID, P.NAME, P.DESCRIPTION, TS.NEW, TS.ACTIVE, TS.SUSPEND, TS.COMPLETE, 
	CASE 
		WHEN TS.ACTIVE > 0 THEN 1
		WHEN TS.SUSPEND > 0 THEN 2
		WHEN TS.COMPLETE > 0 THEN 3
		ELSE 0
	END [STATE],
	TEAMS.NAME TEAM,
	ISNULL(CTE_TIME.WORKTIME, 0.0) / 3600.0 WORKTIME,
	ISNULL(CTE_TIME.ESTIMATEWORKTIME, 0.0) / 3600.0 ESTIMATEWORKTIME,
	ISNULL(PUNCTUALITY,100) PUNCTUALITY
FROM PROJECTS P
JOIN CTE_TASKSTATES TS ON TS.PROJECTID = P.ID 
LEFT JOIN CTE_TIME ON CTE_TIME.PROJECTID = P.ID 
JOIN TEAMS ON TEAMID = TEAMS.ID 

GO

/****** Object:  View [dbo].[V_ACCOUNTSTAT]    Script Date: 13.01.2020 23:38:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER   VIEW [dbo].[V_ACCOUNTSTAT] 
AS
WITH CTE_TASKS AS (
	SELECT ACCOUNTID, COUNT(*) TASKCOUNT FROM TASKS
	WHERE ACCOUNTID IS NOT NULL
	GROUP BY ACCOUNTID
)
,CTE_PROJECTS AS (
	SELECT ACCOUNTID, COUNT(1) PROJECTCOUNT FROM TEAMACCOUNTS
	JOIN PROJECTS ON PROJECTS.TEAMID = TEAMACCOUNTS.TEAMID
	GROUP BY ACCOUNTID
)
,CTE_TIMES AS (
	SELECT ACCOUNTID, SUM(WORKTIME) WORKTIME, SUM(DATEDIFF(SECOND, ESTIMATESTART, DATEADD(DAY,1,ESTIMATEEND))) ESTIMATEWORKTIME, 
		   (1 - (SUM(EXCEEDED+0.0)/COUNT(1)))*100 PUNCTUALITY 
	FROM V_TIMESTAT
	GROUP BY ACCOUNTID
)
SELECT NAME + ' ' + SURNAME DISPLAYNAME, WORKTIME / 3600.0 WORKTIME, ESTIMATEWORKTIME / 3600.0 ESTIMATEWORKTIME, PUNCTUALITY, TASKCOUNT, PROJECTCOUNT FROM CTE_TIMES
JOIN CTE_PROJECTS ON CTE_PROJECTS.ACCOUNTID = CTE_TIMES.ACCOUNTID
JOIN CTE_TASKS ON CTE_TASKS.ACCOUNTID = CTE_TIMES.ACCOUNTID
JOIN MGMNT.ACCOUNTS ON ACCOUNTS.ID = CTE_TASKS.ACCOUNTID
GO

