ALTER TABLE HST.ELEMENTS DROP CONSTRAINT FK_ELEMENTS_ELEMENTVALUES3;
ALTER TABLE HST.ELEMENTS DROP CONSTRAINT FK_ELEMENTS_ELEMENTVALUES4;
ALTER TABLE HST.ELEMENTS DROP COLUMN ELEMENT4;
ALTER TABLE HST.ELEMENTS DROP COLUMN ELEMENT3;
GO

/****** Object:  View [HST].[V_VALUESHISTORY]    Script Date: 13.01.2020 04:04:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER VIEW [HST].[V_VALUESHISTORY]
AS
	SELECT
		 VH.MODUSER,
		 COALESCE(IIF(VH.MODUSERNAME IS NOT NULL AND VH.MODUSERSURNAME IS NOT NULL, VH.MODUSERNAME + ' ' + VH.MODUSERSURNAME, NULL), VH.MODUSERNAME, VH.MODUSERSURNAME) MODUSERDISPLAYNAME,
		 VH.MODDATE,
		 VH.MODCOMP,
		 VH.MODTYPE,
		 A.VALUE AREA,
		 CASE
			WHEN E.LENGTH = 1
				THEN EV0.VALUE
			WHEN E.LENGTH = 2
				THEN EV0.VALUE + ' -> ' + EV1.VALUE
			WHEN E.LENGTH = 3
				THEN EV0.VALUE + ' -> ' + EV1.VALUE + ' -> ' + EV2.VALUE
		 END ELEMENT,
		 P.VALUE [PATH],
		 OV.VALUE OLDVALUE,
		 NV.VALUE NEWVALUE
	FROM HST.VALUESHISTORY VH
	JOIN HST.AREAS A ON A.ID = VH.AREAID
	JOIN HST.PATHS P ON P.TABLENAME = VH.TABLENAME AND P.COLUMNNAME = VH.COLUMNNAME
	JOIN HST.[ELEMENTS] E ON E.TABLENAME = VH.TABLENAME AND E.ROWID = VH.ROWID
	JOIN HST.ELEMENTVALUES EV0 ON EV0.ID = E.ELEMENT0
	LEFT JOIN HST.ELEMENTVALUES EV1 ON EV1.ID = E.ELEMENT1
	LEFT JOIN HST.ELEMENTVALUES EV2 ON EV2.ID = E.ELEMENT2
	LEFT JOIN HST.[VALUES] OV ON OV.ID = VH.OLDVALUEID
	LEFT JOIN HST.[VALUES] NV ON NV.ID = VH.NEWVALUEID
GO

DELETE FROM HST.VALUESHISTORY;
DELETE FROM HST.[VALUES];
DELETE FROM HST.AREAS;
DELETE FROM HST.PATHS;

SET IDENTITY_INSERT HST.AREAS ON;
INSERT INTO HST.AREAS (ID, VALUE) VALUES (1, 'Zadania'), (2, 'Projekty'), (3, 'Zasoby'), (4, 'U¿ytkownicy'), (5, 'Zespo³y');
SET IDENTITY_INSERT HST.AREAS OFF;
GO

INSERT INTO HST.PATHS (TABLENAME, COLUMNNAME, VALUE) VALUES 
('RESOURCES', 'ID', N'Zasób'),
('RESOURCES', 'NAME', N'Zasób -> Nazwa'),
('RESOURCES', 'DESCRIPTION', N'Zasób -> Opis'),
('RESOURCES', 'INUSE', N'Zasób -> W u¿yciu'),
('MGMNT.ACCOUNTS', 'ID', N'Konto u¿ytkownika'),
('MGMNT.ACCOUNTS', 'USERNAME', N'Konto u¿ytkownika -> Nazwa'),
('MGMNT.ACCOUNTS', 'PASSWORD', N'Konto u¿ytkownika -> Has³o'),
('MGMNT.ACCOUNTS', 'PERMISSIONS', N'Konto u¿ytkownika -> Uprawnienia'),
('MGMNT.ACCOUNTS', 'TYPE', N'Konto u¿ytkownika -> Typ konta'),
('MGMNT.ACCOUNTS', 'TITLE', N'Konto u¿ytkownika -> Tytu³'),
('MGMNT.ACCOUNTS', 'NAME', N'Konto u¿ytkownika -> Imiê'),
('MGMNT.ACCOUNTS', 'SURNAME', N'Konto u¿ytkownika -> Nazwisko'),
('MGMNT.ACCOUNTS', 'ISLOCKED', N'Konto u¿ytkownika -> Zablokowane'),
('MGMNT.ACCOUNTS', 'INUSE', N'Konto u¿ytkownika -> W u¿yciu'),
('PROJECTS', 'ID', N'Projekt'),
('PROJECTS', 'NAME', N'Projekt -> W u¿yciu'),
('PROJECTS', 'DESCRIPTION', N'Projekt -> Opis'),
('PROJECTS', 'TEAMID', N'Projekt -> Zespó³'),
('PROJECTS', 'INUSE', N'Projekt -> W u¿yciu'),
('PROJECTRESOURCES', 'ID', N'Projekt -> Zasób'),
('PROJECTRESOURCES', 'COUNT', N'Projekt -> Zasób -> Iloœæ'),
('TASKS', 'ID', N'Zadanie'),
('TASKS', 'NAME', N'Zadanie -> W u¿yciu'),
('TASKS', 'DESCRIPTION', N'Zadanie -> Opis'),
('TASKS', 'STATE', N'Zadanie -> Status'),
('TASKS', 'ACCOUNTID', N'Zadanie -> Wykonawca'),
('TASKS', 'INUSE', N'Zadanie -> W u¿yciu'),
('TASKRESOURCES', 'ID', N'Zadanie -> Zasób'),
('TASKRESOURCES', 'COUNT', N'Zadanie -> Zasób -> Iloœæ'),
('TEAMS', 'ID', N'Zespó³'),
('TEAMS', 'NAME', N'Zespó³ -> W u¿yciu'),
('TEAMS', 'DESCRIPTION', N'Zespó³ -> Opis'),
('TEAMS', 'INUSE', N'Zespó³ -> W u¿yciu'),
('TEAMACCOUNTS', 'ID', N'Zespó³ -> Cz³onek zespo³u')
GO

SET IDENTITY_INSERT HST.[VALUES] ON;
INSERT INTO HST.[VALUES] (ID, [VALUE]) VALUES 
(1, 'Tak'),
(2, 'Nie'),
(3, 'Wewnêtrzne'),
(4, 'Domenowe'),
(5, 'Nowe'),
(6, 'Aktywne'),
(7, 'Wstrzymane'),
(8, 'Zakoñczone');
SET IDENTITY_INSERT HST.[VALUES] OFF;
GO
