CREATE VIEW V_TASKS AS

WITH CTE_ESTIMATESTART AS (
	SELECT * FROM TASKTIMES WHERE TYPE = 0
),
CTE_ESTIMATEEND AS (
	SELECT * FROM TASKTIMES WHERE TYPE = 1
)
SELECT T.ID, T.NAME, T.PROJECTID, ACCOUNTID, A.NAME ACCOUNT, STATE, DESCRIPTION, T.INUSE, ES.TIME ESTIMATESTART, EE.TIME ESTIMATEEND FROM TASKS T
LEFT JOIN CTE_ESTIMATESTART ES ON T.ID = ES.TASKID
LEFT JOIN CTE_ESTIMATEEND EE ON T.ID = EE.TASKID
LEFT JOIN MGMNT.ACCOUNTS A ON A.ID = T.ACCOUNTID 
WHERE T.INUSE = 1